/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rftg_Native */

#ifndef _Included_com_example_rftg_Native
#define _Included_com_example_rftg_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rftg_Native
 * Method:    read_cards
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_rftg_Native_read_1cards
  (JNIEnv *, jclass);

/*
 * Class:     com_example_rftg_Native
 * Method:    init_game
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_rftg_Native_init_1game
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
